### PR TITLE
need graph help

### PR DESCRIPTION
**Pull request by sheppardw**

### CODE REVIEW

**Review by sheppardw — COMMENTED** [review]
Tried to create the pull request for help with the graph that was working before? I am not aware that I changed any code for the graph. Did I create the draft properly?

**Comment by siwelwerd** [comment]
Yep!  Will take a look.

**Comment by sheppardw** [comment]
OHhhh I think it has the old graph name. Like I did not change it when I copied the code. So maybe that's it!

Wendy Sheppard

Instructor
Department of Mathematics
College of Charleston
66 George St.
Charleston, SC 29424-0001
email:  ***@***.***
phone:  843-953-5730
***@***.***?anonymous&ep=bwmEmailSignature>               Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by sheppardw** [comment]
Fixed it!!

Wendy Sheppard

Instructor
Department of Mathematics
College of Charleston
66 George St.
Charleston, SC 29424-0001
email:  ***@***.***
phone:  843-953-5730
***@***.***?anonymous&ep=bwmEmailSignature>               Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by siwelwerd** [comment]
Awesome!  Make any other changes you need to this branch, then mark it as "Ready for review" and we can merge it into main.

**Review by siwelwerd — APPROVED** [review]

**Pull request merged**
