### PR TITLE
Include notes in Slides

### PR DESCRIPTION
**Pull request by siwelwerd**

### CODE REVIEW

**Review by StevenClontz — APPROVED** [review]

**Comment by StevenClontz** [comment]
The fact that we had to do this three times makes me unsure if we (a) should have a monorepo with all the books, or (b) should be factoring out things into even *more* repos lol.

**Comment by siwelwerd** [comment]
We did have a brief conversation about what is the best way to share code among 3 projects, but I recall you saying that it is currently more annoying than worth it due to Github limitations.

**Comment by siwelwerd** [comment]
See [previous discussion](https://github.com/TeamBasedInquiryLearning/linear-algebra/pull/255)

**Comment by StevenClontz** [comment]
*(deletes three lines basically repeating what I said three months ago apparently)*

I think this is a good infrastructure task to tackle before the 2024 edition, but needs more thought...

**Pull request merged**
