### PR TITLE
Stub out Module EQ (#63)

### PR DESCRIPTION
**Pull request by tdegeorge**
#63

### CODE REVIEW

**Review by tdegeorge — COMMENTED** [review]
I tried to fix all my stuff for 01 and 05, but the code chat is not building....Can someone check to make sure it looks correct? I don't know how to read the build from codechat....

**Comment by StevenClontz** [comment]
CodeChat has had some issues recently. I'm not sure if they're fixed yet, but you can try running this command in a terminal then re-running your codespace.

```sh
pip install pretext==2.3.4
```

**Comment by tdegeorge** [comment]
I tried to do that (**I think**) and this is what it says:

Successfully installed pip-24.0 pretext-2.3.7

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip

**Comment by tdegeorge** [comment]
I then tried code chat again and now it won't build :(

**Comment by siwelwerd** [comment]
Looks like you accidentally deleted the `</subsection>` at the end of the activities.  I added it back in, pull this branch and let me know when it's ready for review.  It builds now and I did a quick scan through and it looked okay.

**Review by siwelwerd — APPROVED** [review]

**Pull request merged**
