### PR TITLE
EL4 first draft

### PR DESCRIPTION
**Pull request by AbbyANoble**
Ready to go, except I'm making an issue for one wonky graph!

### CODE REVIEW

**Comment by AbbyANoble** [comment]
Oh! And the 2 columns of answer choices in 5.4.5b were weirdly formatted again in my codechat, like before in #185.

**Comment by siwelwerd** [comment]
>Oh! And the 2 columns of answer choices in 5.4.5b were weirdly formatted again in my codechat, like before in https://github.com/TeamBasedInquiryLearning/precalculus/issues/185.

Try typing `pretext --version` into the terminal.  I am guessing it says 2.3.4.  If this is the case, don't worry about it and it will be fixed in the deployment, which uses the newer version (2.4.1) that fixes this bug.

P.S. @StevenClontz Should we just go ahead and update requirements.txt to 2.4.1?

**Review by siwelwerd — APPROVED** [review]

**Comment by AbbyANoble** [comment]
> Try typing `pretext --version` into the terminal. I am guessing it says 2.3.4. 

Yep! That's what it said!

**Comment by StevenClontz** [comment]
Once #246 is merged you can either recreate your codespace, or run

`pip install -r requirements.txt`

in a Terminal window to upgrade PreTeXt. (Or just run `pip install --upgrade pretext` now.)

**Pull request merged**
